name: todo_backend_pipeline

on:
  push:
    branches:
      - master

jobs:

  starting:
    runs-on: ubuntu-latest
    name: starting
    steps:
      - name: Starting
        run: echo "starting"

  setup:
    runs-on: ubuntu-latest
    name: Setup
    steps:
      - uses: actions/checkout@v4

  deploy:
    runs-on: ubuntu-latest
    name: Upload files
    steps:
      - name: upload_files
        uses: nogsantos/scp-deploy@master
        with:
          src: './*'
          host: ${{ secrets.HOST_IP }}
          remote: ${{ secrets.HOST_DIRECTORY }}
          port: ${{ secrets.HOST_PORT }}
          user: ${{ secrets.HOST_USER }}
          key: ${{ secrets.RSA_KEY }}