name: todo_backend_pipeline

on:
  push:
    branches:
      - master

jobs:

  starting:
    runs-on: ubuntu-latest
    name: Starting
    steps:
      - name: Starting
        run: echo "starting"

  setup:
    runs-on: ubuntu-latest
    name: Setup
    steps:
      - uses: actions/checkout@v4                  
      - run: echo "starting..."
      - name: Deploy to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST_IP }}
          username: ${{ secrets.HOST_USER }}
          password: ${{ secrets.HOST_PASSWORD }}
          key: ${{ secrets.RSA_KEY }}
          port: ${{ secrets.HOST_PORT }}
          source: "./models/*"
          target: "~/opt"
          debug: true
          rm: true