name: todo_backend_pipeline

on:
  push:
    branches:
      - master

jobs:  

  build:
    runs-on: ubuntu-latest
    name: Build Go for Linux
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.5
      - name: Build Go binary for Linux
        run: |
          GOOS=linux GOARCH=amd64 go build -o todo_backend main.go
      - name: List output files
        run: ls -alh ./todo_backend
      - name: Check directory content before deploy 1
        run: ls
      - name: Check directory content before deploy
        run: ls -alh ./todo_backend
      - name : Deploy to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST_IP }}
          username: ${{ secrets.HOST_USER }}          
          key: ${{ secrets.RSA_KEY }}
          port: ${{ secrets.HOST_PORT }}
          target: ${{ secrets.HOST_DIRECTORY }}
          source: "./todo_backend"
          rm: false        

  # setup:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   name: Setup
  #   steps:
  #     - name: Check directory content before deploy 1
  #       run: ls
  #     - name: Check directory content before deploy
  #       run: ls -alh ./todo_backend
  #     - name : Deploy to server
  #       uses: appleboy/scp-action@v0.1.7
  #       with:
  #         host: ${{ secrets.HOST_IP }}
  #         username: ${{ secrets.HOST_USER }}          
  #         key: ${{ secrets.RSA_KEY }}
  #         port: ${{ secrets.HOST_PORT }}
  #         target: ${{ secrets.HOST_DIRECTORY }}
  #         source: "./todo_backend"
  #         rm: false

  start_app:
    needs: build
    runs-on: ubuntu-latest
    name: Start Application
    steps:      
      - name: Executing remote SSH commands
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST_IP }}
          username: ${{ secrets.HOST_USER }}
          key: ${{ secrets.RSA_KEY }}
          port: ${{ secrets.HOST_PORT }}
          script: |  
            cd ~/../opt
            chmod +x todo_backend
            nohup ./todo_backend > todo_backend.log 2>&1 &