name: todo_backend_pipeline

on:
  push:
    branches: 
      - master

jobs:

  setup:
    name: setup
    runs-on: ubtuntu-latest    
    steps:
      - name: Set up go
        uses: actions/setup-go@v3
        with:
          go-version: 1.22.5

  checkout:  
    name: check_out
    runs-on: ubtuntu-latest
    steps:
      - name: first_checkout      
        uses: actions/checkout@v3

  deploy:        
      name: Upload files
      runs-on: ubuntu-latest
      steps: 
        - name: upload_files
          uses: actions/nogsantos/scp-deploy@master
          with:
            src: './*'
            remote: ${{ secrets.HOST_DIRECTORY }}
            host: ${{ secrets.HOST_IP }}
            user: ${{ secrets.HOST_USER }}
            port: ${{ secrets.HOST_PORT }}
            key: ${{ secrets.RSA_KEY }}